export const dailyInventoryModel = {
  moduleName: "daily-inventory",
  tableName: "public.daily_inventory",
  primaryKey: "id",
  routePath: "/api/daily-inventory",
  defaultOrderBy: "inventory_date",
  filterableFields: ["id", "hotel_id", "room_type_id", "inventory_date", "stop_sell", "closed"],
  searchableFields: [],
  createFields: [
    "hotel_id",
    "room_type_id",
    "inventory_date",
    "total_inventory",
    "sold_inventory",
    "available_inventory",
    "stop_sell",
    "closed",
  ],
  updateFields: [
    "hotel_id",
    "room_type_id",
    "inventory_date",
    "total_inventory",
    "sold_inventory",
    "available_inventory",
    "stop_sell",
    "closed",
  ],
};
