export const facilitiesModel = {
  moduleName: "facilities",
  tableName: "public.facilities",
  primaryKey: "id",
  routePath: "/api/facilities",
  defaultOrderBy: "created_at",
  filterableFields: ["id", "hotel_id", "code", "facility_type", "price_type", "is_active"],
  searchableFields: ["code", "name", "description", "facility_type"],
  createFields: [
    "hotel_id",
    "code",
    "name",
    "description",
    "facility_type",
    "price_type",
    "base_price",
    "is_active",
  ],
  updateFields: [
    "hotel_id",
    "code",
    "name",
    "description",
    "facility_type",
    "price_type",
    "base_price",
    "is_active",
  ],
};
