export const hotelsModel = {
  moduleName: "hotels",
  tableName: "public.hotels",
  primaryKey: "id",
  routePath: "/api/hotels",
  defaultOrderBy: "created_at",
  filterableFields: ["id", "code", "brand", "country", "city", "district", "status"],
  searchableFields: ["code", "name", "brand", "country", "city", "district", "address"],
  createFields: [
    "code",
    "name",
    "brand",
    "country",
    "city",
    "district",
    "address",
    "latitude",
    "longitude",
    "star_rating",
    "timezone",
    "checkin_time",
    "checkout_time",
    "total_rooms",
    "status",
  ],
  updateFields: [
    "code",
    "name",
    "brand",
    "country",
    "city",
    "district",
    "address",
    "latitude",
    "longitude",
    "star_rating",
    "timezone",
    "checkin_time",
    "checkout_time",
    "total_rooms",
    "status",
  ],
  updatedAtField: "updated_at",
};
