export const promotionsModel = {
  moduleName: "promotions",
  tableName: "public.promotions",
  primaryKey: "id",
  routePath: "/api/promotions",
  defaultOrderBy: "valid_from",
  filterableFields: ["id", "code", "discount_type", "active"],
  searchableFields: ["code", "name"],
  createFields: [
    "code",
    "name",
    "discount_type",
    "discount_value",
    "valid_from",
    "valid_to",
    "usage_limit",
    "active",
  ],
  updateFields: [
    "code",
    "name",
    "discount_type",
    "discount_value",
    "valid_from",
    "valid_to",
    "usage_limit",
    "active",
  ],
};
