export const roomTypesModel = {
  moduleName: "room-types",
  tableName: "public.room_types",
  primaryKey: "id",
  routePath: "/api/room-types",
  defaultOrderBy: "created_at",
  filterableFields: ["id", "hotel_id", "code", "bed_type", "smoking_allowed"],
  searchableFields: ["code", "name", "description", "bed_type"],
  createFields: [
    "hotel_id",
    "code",
    "name",
    "description",
    "room_size",
    "max_adults",
    "max_children",
    "bed_type",
    "smoking_allowed",
    "base_price",
    "total_inventory",
  ],
  updateFields: [
    "hotel_id",
    "code",
    "name",
    "description",
    "room_size",
    "max_adults",
    "max_children",
    "bed_type",
    "smoking_allowed",
    "base_price",
    "total_inventory",
  ],
  updatedAtField: "updated_at",
};
