export const dailyRatesModel = {
  moduleName: "daily-rates",
  tableName: "public.daily_rates",
  primaryKey: "id",
  routePath: "/api/daily-rates",
  defaultOrderBy: "rate_date",
  filterableFields: ["id", "hotel_id", "room_type_id", "rate_plan_id", "rate_date", "currency", "stop_sell", "closed"],
  searchableFields: [],
  createFields: [
    "hotel_id",
    "room_type_id",
    "rate_plan_id",
    "rate_date",
    "base_rate",
    "occupancy_factor",
    "season_factor",
    "weekend_factor",
    "event_factor",
    "demand_factor",
    "final_rate",
    "currency",
    "stop_sell",
    "closed",
  ],
  updateFields: [
    "hotel_id",
    "room_type_id",
    "rate_plan_id",
    "rate_date",
    "base_rate",
    "occupancy_factor",
    "season_factor",
    "weekend_factor",
    "event_factor",
    "demand_factor",
    "final_rate",
    "currency",
    "stop_sell",
    "closed",
  ],
};
